name: add-action-build-result

on:
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    build-and-add-result:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
            - name: Enable Corepack
              run: corepack enable
            - run: |
                  pnpm install && pnpm run build
                  git add .
                  if ! git diff-index --quiet HEAD; then
                    git config --global user.name 'npayfebot'
                    git config --global user.email 'npay.fe.bot@navercorp.com'
                    git commit -m "✨ add action build result"
                    git push origin ${{ github.head_ref }}
                  else
                    echo "Action 빌드 결과물에 변경점이 없습니다."
                  fi
