name: CI
on:
    pull_request:
        branches:
            - '**'

jobs:
    PrettierAndLint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
                  run_install: true
            - run: pnpm run prettier
            - run: pnpm run lint
            - run: pnpm run markdownlint

    Test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
                  run_install: true
            - run: pnpm run test
